spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/travis?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root1234
  resources:
    add-mappings: false
  application:
    name: travis

---